apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  namespace: arogya
  labels:
    app: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: imadhifham/telemedicine-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: telemedicine-config
            - secretRef:
                name: telemedicine-secret
          readinessProbe:
            httpGet:
              path: /api/v1/telemedicine/health
              port: 8086
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/telemedicine/health
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
