apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
  namespace: arogya
  labels:
    app: telemedicine-service
spec:
  type: ClusterIP
  selector:
    app: telemedicine-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
