apiVersion: v1
kind: Secret
metadata:
  name: appointment-secret
  namespace: arogya
type: Opaque
stringData:
  DB_PASSWORD: "CHANGE_ME_APPOINTMENT_DB_PASSWORD"
  JWT_SECRET: "CHANGE_ME_APPOINTMENT_JWT_SECRET"
