apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: arogya
type: Opaque
stringData:
  MONGODB_URI: "CHANGE_ME_MONGODB_URI_FOR_AUTH"
  JWT_SECRET: "CHANGE_ME_AUTH_JWT_SECRET"
  JWT_REFRESH_SECRET: "CHANGE_ME_AUTH_REFRESH_SECRET"
