apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: arogya
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: imadhifham/appointment-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: appointment-config
            - secretRef:
                name: appointment-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 45
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
