apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-config
  namespace: arogya
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SERVER_PORT: "8084"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/arogya_appointments"
  SPRING_DATASOURCE_USERNAME: "arogya"
