apiVersion: v1
kind: ConfigMap
metadata:
  name: telemedicine-config
  namespace: arogya
data:
  NODE_ENV: "production"
  PORT: "8086"
  SERVICE_NAME: "telemedicine-service"
  REQUEST_TIMEOUT_MS: "5000"
  ROOM_DEFAULT_EXPIRY_HOURS: "2"
  JITSI_BASE_URL: "https://meet.jit.si"
  PATIENT_SERVICE_URL: "http://patient-service:8082"
  DOCTOR_SERVICE_URL: "http://doctor-service:8083"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:8084"
