spring.datasource.url=jdbc:postgresql://postgres-appointment:5432/arogya_appointments
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=redis

jwt.secret=${JWT_SECRET}

services.doctor.url=http://doctor-service:8082
services.payment.url=http://payment-service:3001
services.notification.url=http://notification-service:3002
services.telemedicine.url=http://telemedicine-service:3003